services:
  varatiya-app:
    build: .
    image: varatiya-app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_mysql_password
      - DB_NAME=tenant_management
      - DB_PORT=3306
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=10
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/varatiya-app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
